### ISSUE TITLE
Points reward reason

### ISSUE THREAD

**Issue by Uafinder** [ducdhm/kpoll#13]
I suppose that here no need to display poll id in the reason field while allocating points. Only for debugging.
![image](https://cloud.githubusercontent.com/assets/1945230/10524895/97e6ece6-738a-11e5-8f23-c7f1a5bb96af.png)

**Comment by ducdhm** [comment]
Done!

**Comment by Uafinder** [comment]
Good, but the name of the poll would be great to leave.
Should be like "Answered poll with name = "Poll name"

**Comment by Uafinder** [comment]
Yup!
