### ISSUE TITLE
Group membership doesn't check while awarding points

### ISSUE THREAD

**Issue by Uafinder** [ducdhm/kpoll#14]
I've a user sp093 which in admins group, and points bucket which has not this group in it's active list. However, when sp093 answered a poll, he was awarded by points. Which is incorrect.
![image](https://cloud.githubusercontent.com/assets/1945230/10525156/d0e8840e-738b-11e5-84d7-45f4ea4860b9.png)
![image](https://cloud.githubusercontent.com/assets/1945230/10525167/dfe634a6-738b-11e5-9ab3-07b27f5ff875.png)
![image](https://cloud.githubusercontent.com/assets/1945230/10525180/ec890e36-738b-11e5-85fb-ee7944342552.png)
![image](https://cloud.githubusercontent.com/assets/1945230/10525197/f9cf8426-738b-11e5-97f5-1ac39ed4f238.png)

**Comment by ducdhm** [comment]
Done!

**Comment by Uafinder** [comment]
Yup!
