### ISSUE TITLE
When there no enabled poll "You don't have any poll for now" text is doubling too. 

### ISSUE THREAD

**Issue by ducdhm** [ducdhm/kpoll#2]
![eb018e86-7263-11e5-8a9d-738abd631671](https://cloud.githubusercontent.com/assets/1289631/10480969/d9e9ff0a-7297-11e5-94bc-ce986f7faf30.png)

**Comment by ducdhm** [comment]
Done!

**Comment by Uafinder** [comment]
![image](https://cloud.githubusercontent.com/assets/1945230/10559123/420edf6e-74f1-11e5-860a-8c2744cd87fe.png)
The same

**Comment by ducdhm** [comment]
Let's move to https://github.com/ducdhm/kpoll/issues/18
