### ISSUE TITLE
When poll are visible for two or more groups Learners are don't see it

### ISSUE THREAD

**Issue by Uafinder** [ducdhm/kpoll#25]
For example. User is a member of Learners group. Poll should be visible for Learners and Admins. And user doesn't see it.
vladqa098@mailinator.com
qwerty1

**Comment by ducdhm** [comment]
Can you show me step by step to reproduce?
I use your user and everything's fine

**Comment by bradmac** [comment]
ping

**Comment by Uafinder** [comment]
looks like ok now, weird, closing for now
