### ISSUE TITLE
The polls are visible only for members of administrators group

### ISSUE THREAD

**Issue by ducdhm** [ducdhm/kpoll#3]
The polls are visible only for members of administrators group. If i have a user which is part of Learners and assign a poll to Learners group user doesn't see it. This is possible connected to absent appropriate security role for group.

![54b6c65c-7264-11e5-9704-51c96dde8817](https://cloud.githubusercontent.com/assets/1289631/10480995/fba624ac-7297-11e5-85ab-f990b666c349.png)
![613863e0-7264-11e5-8941-100809b9d381](https://cloud.githubusercontent.com/assets/1289631/10480996/fbb54f54-7297-11e5-95b1-ff7290969a16.png)
![eb018e86-7263-11e5-8a9d-738abd631671](https://cloud.githubusercontent.com/assets/1289631/10480997/fbb7c3ba-7297-11e5-8a5b-3d9cd1b56d39.png)

**Comment by ducdhm** [comment]
@tuzzmaniandevil Hey Mr Wes, please kindly help me this issue :D

**Comment by ducdhm** [comment]
Fixed!

**Comment by Uafinder** [comment]
Ok, now
