### ISSUE TITLE
Answering are also doubling

### ISSUE THREAD

**Issue by ducdhm** [ducdhm/kpoll#4]
![7e52a1d4-7269-11e5-8c05-11e630e0c64c](https://cloud.githubusercontent.com/assets/1289631/10481010/1744fda0-7298-11e5-8adb-6b6ab9e14d1e.png)

**Comment by ducdhm** [comment]
Done!

**Comment by Uafinder** [comment]
The same :(

**Comment by ducdhm** [comment]
Let's move to https://github.com/ducdhm/kpoll/issues/18
