### ISSUE TITLE
"See result" also doubles information.

### ISSUE THREAD

**Issue by ducdhm** [ducdhm/kpoll#7]
![0c85e0a6-726a-11e5-8f4a-fb2be0faab32](https://cloud.githubusercontent.com/assets/1289631/10481036/4b896006-7298-11e5-98ca-ddaf0b72605c.png)

**Comment by ducdhm** [comment]
Done!

**Comment by Uafinder** [comment]
The same

**Comment by ducdhm** [comment]
Let's move to https://github.com/ducdhm/kpoll/issues/18
