### ISSUE TITLE
Bug when you tries to create a poll more than one without refreshing page

### ISSUE THREAD

**Issue by ducdhm** [ducdhm/kpoll#8]
Steps to reproduce:
-push add new poll button
-push cancel or x buttons
-push add new poll button again
-watch a bug

![ac966bb8-726c-11e5-94b7-5af8718b5f6e](https://cloud.githubusercontent.com/assets/1289631/10481059/704a162e-7298-11e5-8bcb-0d60a8be1255.png)

**Comment by Uafinder** [comment]
Yup, looks ok
